# Generated by Django 6.0.3 on 2026-03-25 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='saved_villas',
            field=models.ManyToManyField(blank=True, to='villas.villa'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
