# Generated by Django 6.0.3 on 2026-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_villas',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='villas.villa'),
        ),
    ]
