# Generated by Django 6.0.3 on 2026-04-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_dob_user_emergency_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='saved_villas',
        ),
    ]
