# Generated by Django 6.0.3 on 2026-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('distance_to_station', models.CharField(max_length=100)),
                ('guests', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('price', models.IntegerField()),
                ('nights', models.IntegerField(default=1)),
                ('rating', models.FloatField(default=4.0)),
                ('image', models.ImageField(upload_to='villa_images/')),
                ('amenities', models.JSONField()),
            ],
        ),
    ]
