# Generated by Django 6.0.3 on 2026-04-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('read_time', models.CharField(max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blogs/hero/')),
                ('intro', models.TextField()),
                ('section1_title', models.CharField(blank=True, max_length=255)),
                ('section1_text', models.TextField(blank=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blogs/section1/')),
                ('section2_title', models.CharField(blank=True, max_length=255)),
                ('section2_text', models.TextField(blank=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blogs/section2/')),
                ('section3_title', models.CharField(blank=True, max_length=255)),
                ('section3_text', models.TextField(blank=True)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blogs/section3/')),
                ('conclusion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
