# Generated by Django 6.0.3 on 2026-04-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/title/'),
        ),
    ]
