# Generated by Django 5.2.9 on 2026-03-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
