# Generated by Django 6.0.3 on 2026-04-11 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_alter_villa_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villa',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='villa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='villa',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='villa',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
