# Generated by Django 6.0.3 on 2026-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0003_alter_villa_options_villa_created_at_villa_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
